<a href="https://colab.research.google.com/github/Shekinahh/boot-camp-gdsc/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd

In [26]:
data_path = "/hour.csv"
data = pd.read_csv(data_path)
data.describe()

,instant,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,17379.0000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000
mean,8690.0000,2.501640,0.502561,6.537775,11.546752,0.028770,3.003683,0.682721,1.425283,0.496987,0.475775,0.627229,0.190098,35.676218,153.786869,189.463088
std,5017.0295,1.106918,0.500008,3.438776,6.914405,0.167165,2.005771,0.465431,0.639357,0.192556,0.171850,0.192930,0.122340,49.305030,151.357286,181.387599
min,1.0000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,4345.5000,2.000000,0.000000,4.000000,6.000000,0.000000,1.000000,0.000000,1.000000,0.340000,0.333300,0.480000,0.104500,4.000000,34.000000,40.000000
50%,8690.0000,3.000000,1.000000,7.000000,12.000000,0.000000,3.000000,1.000000,1.000000,0.500000,0.484800,0.630000,0.194000,17.000000,115.000000,142.000000
75%,13034.5000,3.000000,1.000000,10.000000,18.000000,0.000000,5.000000,1.000000,2.000000,0.660000,0.621200,0.780000,0.253700,48.000000,220.000000,281.000000
max,17379.0000,4.000000,1.000000,12.000000,23.000000,1.000000,6.000000,1.000000,4.000000,1.000000,1.000000,1.000000,0.850700,367.000000,886.000000,977.000000

In [28]:
data.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [29]:
y = data.registered
data_features = ['weathersit','weekday','hr']
X=data[data_features]
X.describe()

         weathersit       weekday            hr
count  17379.000000  17379.000000  17379.000000
mean       1.425283      3.003683     11.546752
std        0.639357      2.005771      6.914405
min        1.000000      0.000000      0.000000
25%        1.000000      1.000000      6.000000
50%        1.000000      3.000000     12.000000
75%        2.000000      5.000000     18.000000
max        4.000000      6.000000     23.000000

In [30]:
X.head()

   weathersit  weekday  hr
0           1        6   0
1           1        6   1
2           1        6   2
3           1        6   3
4           1        6   4

In [32]:
from sklearn.tree import DecisionTreeRegressor

data_model = DecisionTreeRegressor(random_state=1)

data_model.fit(X,y)

DecisionTreeRegressor(random_state=1)

In [33]:
print("making prediction")
print(X.head())
print("prediction are")
print(data_model.predict(X.head()))

making prediction
   weathersit  weekday  hr
0           1        6   0
1           1        6   1
2           1        6   2
3           1        6   3
4           1        6   4
prediction are
[87.55263158 60.26865672 43.24242424 18.44444444  5.84507042]